# install: pre-commit install --hook-type pre-commit --hook-type pre-push --hook-type pre-merge-commit
default_language_version:
  python: python3.11
repos:
-   repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
    -   id: black
        args: [--safe]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    # -   id: check-added-large-files
    -   id: debug-statements
        language_version: python3

-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        language_version: python3

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
    -   id: reorder-python-imports
        args: [--py36-plus]

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.8.0
#     hooks:
#     -   id: mypy

-   repo: local
    hooks:
    -   id: update-version
        name: update-version
        entry: python update_version.py
        language: system
        pass_filenames: false
        stages: [pre-commit, pre-merge-commit]
    -   id: mypy
        name: mypy
        entry: mypy .
        language: system
        pass_filenames: false
        always_run: true
